ci: test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -115,47 +115,48 @@ jobs:
 #      - uses: dtolnay/rust-toolchain@clippy
 #      - run: cargo clippy --tests -- -Dwarnings #-Dclippy::all #-Dclippy::pedantic
 #
-  machete:
-    name: Unused Dependencies
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Installation
-      uses: taiki-e/install-action@v2
-      with:
-        tool: cargo-machete
-    - name: Cargo Machete
-      run: |
-        cargo machete
-        exit_code=$?
-        if [ $exit_code = 0 ]; then
-          echo "Found unused dependencies"
-          exit $exit_code
-        fi
-
-  sort:
-    name: Cargo Sorted
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Installation
-        uses: taiki-e/install-action@v2
-        with:
-          tool: cargo-sort
-
-      - name: Check if Cargo.toml is sorted
-        run: |
-          cargo sort -wc
-          exit_code=$?
-          if [ $exit_code != 0 ]; then
-            echo "Cargo.toml is not sorted. Run `cargo sort -w` to fix it."
-            exit $exit_code
-          fi
-
-env:
-  #RUSTFLAGS: -Dwarnings
-  CARGO_INCREMENTAL: 0 # on large changes this just bloats ./target
-  RUST_BACKTRACE: short
-  CARGO_NET_RETRY: 10
-  RUSTUP_MAX_RETRIES: 10
+#  # they have their own GHA, but it uses `cargo install`. Until they transfer to binstall, this is better.
+#  machete:
+#    name: Unused Dependencies
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#    - name: Installation
+#      uses: taiki-e/install-action@v2
+#      with:
+#        tool: cargo-machete
+#    - name: Cargo Machete
+#      run: |
+#        cargo machete
+#        exit_code=$?
+#        if [ $exit_code = 0 ]; then
+#          echo "Found unused dependencies"
+#          exit $exit_code
+#        fi
+#
+#  sort:
+#    name: Cargo Sorted
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Installation
+#        uses: taiki-e/install-action@v2
+#        with:
+#          tool: cargo-sort
+#
+#      - name: Check if Cargo.toml is sorted
+#        run: |
+#          cargo sort -wc
+#          exit_code=$?
+#          if [ $exit_code != 0 ]; then
+#            echo "Cargo.toml is not sorted. Run `cargo sort -w` to fix it."
+#            exit $exit_code
+#          fi
+#
+#env:
+#  #RUSTFLAGS: -Dwarnings
+#  CARGO_INCREMENTAL: 0 # on large changes this just bloats ./target
+#  RUST_BACKTRACE: short
+#  CARGO_NET_RETRY: 10
+#  RUSTUP_MAX_RETRIES: 10
