ci: wip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,11 +16,12 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v4
 
     - name: Install tokei
-      run: |
-        cargo install tokei
+      uses: cargo-bins/cargo-binstall@main
+      with:
+        tool: tokei
 
     - name: Run tokei and save output to json file
       run: tokei -o json > tokei_output.json
@@ -39,100 +40,100 @@ jobs:
         else
           echo "Check passed: Number of comments is less than 10% of code"
         fi
-
-  pre_ci:
-    uses: valeratrades/.github/.github/workflows/pre_ci.yml@master
-
-  test:
-    name: Rust ${{matrix.rust}}
-    needs: pre_ci
-    if: needs.pre_ci.outputs.continue
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        rust: [nightly, stable] # dtolnay had [nightly, beta, stable, 1.70.0], hence the matrix
-    timeout-minutes: 45
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: ${{matrix.rust}}
-      # test this works
-      - name: Set RUSTFLAGS for release branch
-        run: echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
-        if: github.ref == 'refs/heads/release'
-      - name: Enable type layout randomization
-        run: echo RUSTFLAGS=${RUSTFLAGS}\ -Zrandomize-layout\ --cfg=exhaustive >> $GITHUB_ENV
-        if: matrix.rust == 'nightly'
-      # not sure why dtolnay has this
-      #- run: cargo check --locked
-      - run: cargo update
-      - run: cargo check
-      - run: cargo test
-      #TODO: figure this out
-      #  if: matrix.os == 'ubuntu' && matrix.rust == 'nightly'
-      #- run: cargo run -- expand --manifest-path tests/Cargo.toml > expand.rs && diff tests/lib.expand.rs expand.rs
-
-  doc:
-    name: Documentation
-    needs: pre_ci
-    if: needs.pre_ci.outputs.continue
-    runs-on: ubuntu-latest
-    timeout-minutes: 45
-    env:
-      RUSTDOCFLAGS: -Dwarnings
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@nightly
-      - uses: dtolnay/install@cargo-docs-rs
-      - run: cargo docs-rs
-
-  miri:
-    name: Miri
-    needs: pre_ci
-    if: needs.pre_ci.outputs.continue
-    runs-on: ubuntu-latest
-    timeout-minutes: 45
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@miri
-      - run: cargo miri setup
-      - run: cargo miri test
-        env:
-          MIRIFLAGS: -Zmiri-strict-provenance
-
-  clippy:
-    name: Clippy
-    runs-on: ubuntu-latest
-    if: github.event_name != 'pull_request'
-    timeout-minutes: 45
-    steps:
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@clippy
-      - run: cargo clippy --tests -- -Dwarnings #-Dclippy::all #-Dclippy::pedantic
-
-  machete:
-    name: Unused Dependencies
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Install cargo-machete
-      run: |
-        cargo install cargo-machete
-
-    - name: Cargo Machete
-      run: |
-        cargo machete
-        exit_code=$?
-        if [ $exit_code = 0 ]; then
-          echo "Found unused dependencies"
-          exit $exit_code
-        fi
-
-env:
-  #RUSTFLAGS: -Dwarnings
-  CARGO_INCREMENTAL: 0 # on large changes this just bloats ./target
-  RUST_BACKTRACE: short
-  CARGO_NET_RETRY: 10
-  RUSTUP_MAX_RETRIES: 10
+#
+#  pre_ci:
+#    uses: valeratrades/.github/.github/workflows/pre_ci.yml@master
+#
+#  test:
+#    name: Rust ${{matrix.rust}}
+#    needs: pre_ci
+#    if: needs.pre_ci.outputs.continue
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        rust: [nightly, stable] # dtolnay had [nightly, beta, stable, 1.70.0], hence the matrix
+#    timeout-minutes: 45
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: dtolnay/rust-toolchain@master
+#        with:
+#          toolchain: ${{matrix.rust}}
+#      # test this works
+#      - name: Set RUSTFLAGS for release branch
+#        run: echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
+#        if: github.ref == 'refs/heads/release'
+#      - name: Enable type layout randomization
+#        run: echo RUSTFLAGS=${RUSTFLAGS}\ -Zrandomize-layout\ --cfg=exhaustive >> $GITHUB_ENV
+#        if: matrix.rust == 'nightly'
+#      # not sure why dtolnay has this
+#      #- run: cargo check --locked
+#      - run: cargo update
+#      - run: cargo check
+#      - run: cargo test
+#      #TODO: figure this out
+#      #  if: matrix.os == 'ubuntu' && matrix.rust == 'nightly'
+#      #- run: cargo run -- expand --manifest-path tests/Cargo.toml > expand.rs && diff tests/lib.expand.rs expand.rs
+#
+#  doc:
+#    name: Documentation
+#    needs: pre_ci
+#    if: needs.pre_ci.outputs.continue
+#    runs-on: ubuntu-latest
+#    timeout-minutes: 45
+#    env:
+#      RUSTDOCFLAGS: -Dwarnings
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: dtolnay/rust-toolchain@nightly
+#      - uses: dtolnay/install@cargo-docs-rs
+#      - run: cargo docs-rs
+#
+#  miri:
+#    name: Miri
+#    needs: pre_ci
+#    if: needs.pre_ci.outputs.continue
+#    runs-on: ubuntu-latest
+#    timeout-minutes: 45
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: dtolnay/rust-toolchain@miri
+#      - run: cargo miri setup
+#      - run: cargo miri test
+#        env:
+#          MIRIFLAGS: -Zmiri-strict-provenance
+#
+#  clippy:
+#    name: Clippy
+#    runs-on: ubuntu-latest
+#    if: github.event_name != 'pull_request'
+#    timeout-minutes: 45
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: dtolnay/rust-toolchain@clippy
+#      - run: cargo clippy --tests -- -Dwarnings #-Dclippy::all #-Dclippy::pedantic
+#
+#  machete:
+#    name: Unused Dependencies
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#    - name: Install cargo-machete
+#      run: |
+#        cargo install cargo-machete
+#
+#    - name: Cargo Machete
+#      run: |
+#        cargo machete
+#        exit_code=$?
+#        if [ $exit_code = 0 ]; then
+#          echo "Found unused dependencies"
+#          exit $exit_code
+#        fi
+#
+#env:
+#  #RUSTFLAGS: -Dwarnings
+#  CARGO_INCREMENTAL: 0 # on large changes this just bloats ./target
+#  RUST_BACKTRACE: short
+#  CARGO_NET_RETRY: 10
+#  RUSTUP_MAX_RETRIES: 10
